// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeIt.Models;

namespace TimeIt.Migrations
{
    [DbContext(typeof(TimeItDbContext))]
    [Migration("20190307035126_Interval_Update")]
    partial class Interval_Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("TimeIt.Models.Interval", b =>
                {
                    b.Property<int>("IntervalID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color")
                        .IsRequired();

                    b.Property<int>("Duration");

                    b.Property<string>("Name");

                    b.Property<int>("Position");

                    b.Property<int>("TimerID");

                    b.HasKey("IntervalID");

                    b.HasIndex("TimerID");

                    b.HasIndex("TimerID", "Position")
                        .IsUnique();

                    b.ToTable("Intervals");

                    b.HasData(
                        new
                        {
                            IntervalID = 1,
                            Color = "#FFFFFF00",
                            Duration = 180,
                            Name = "Workout",
                            Position = 1,
                            TimerID = 1
                        },
                        new
                        {
                            IntervalID = 2,
                            Color = "#FF0000FF",
                            Duration = 40,
                            Name = "Rest",
                            Position = 2,
                            TimerID = 1
                        },
                        new
                        {
                            IntervalID = 3,
                            Color = "#FFFF0000",
                            Duration = 90,
                            Name = "Run",
                            Position = 3,
                            TimerID = 1
                        });
                });

            modelBuilder.Entity("TimeIt.Models.Timer", b =>
                {
                    b.Property<int>("TimerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Repetitions");

                    b.HasKey("TimerID");

                    b.ToTable("Timers");

                    b.HasData(
                        new
                        {
                            TimerID = 1,
                            Name = "Default",
                            Repetitions = 2
                        });
                });

            modelBuilder.Entity("TimeIt.Models.Interval", b =>
                {
                    b.HasOne("TimeIt.Models.Timer", "Timer")
                        .WithMany("Intervals")
                        .HasForeignKey("TimerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
